apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/kubeflow/components/crud-web-apps/tensorboards/manifests/overlays/istio?ref=c4302feefee455f0f6b4e8b827770bfe17b440cc # tag=v1.4-rc.0

images:
- name: public.ecr.aws/j1r0q0g6/notebooks/tensorboards-web-app
  newName: public.ecr.aws/j1r0q0g6/notebooks/tensorboards-web-app
  newTag: v1.4-rc.1
