apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/kubeflow/components/crud-web-apps/tensorboards/manifests/overlays/istio?ref=29ef970492ddbdbc83438276e60a2a38daf4f638 # tag=v1.4-rc.1

images:
- name: public.ecr.aws/j1r0q0g6/notebooks/tensorboards-web-app
  newName: public.ecr.aws/j1r0q0g6/notebooks/tensorboards-web-app
  newTag: v1.4-rc.1
