apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-applications/argocd.yaml

## Common
- argocd-applications/istio-operator.yaml
- argocd-applications/istio.yaml
- argocd-applications/istio-resources.yaml

- argocd-applications/certificates.yaml
- argocd-applications/external-secrets.yaml
- argocd-applications/sealed-secrets.yaml

# Pick *one* of the following two applications
# - argocd-applications/cert-manager-dns-01.yaml
- argocd-applications/cert-manager-self-signing.yaml

## Auth
- argocd-applications/dex.yaml
- argocd-applications/oauth2-proxy.yaml
- argocd-applications/oidc-auth.yaml

## Kubeflow
- argocd-applications/central-dashboard.yaml
- argocd-applications/profile-controller_access-management.yaml
- argocd-applications/kubeflow-namespace.yaml
- argocd-applications/kubeflow-roles.yaml
- argocd-applications/pipelines.yaml
- argocd-applications/pod-defaults.yaml
# - argocd-applications/katib.yaml
- argocd-applications/jupyter-web-app.yaml
- argocd-applications/notebook-controller.yaml
- argocd-applications/volumes-web-app.yaml
# - argocd-applications/training-operator.yaml
# - argocd-applications/tensorboard-controller.yaml
# - argocd-applications/tensorboards-web-app.yaml

## Ray
- argocd-applications/ray-operator.yaml

## Monitoring
- argocd-applications/kiali.yaml
- argocd-applications/loki-stack.yaml
- argocd-applications/monitoring-resources.yaml
