apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- ../../base
- secret.yaml

patchesStrategicMerge:
- patches/configmap-patch.yaml

images:
- name: ghcr.io/dexidp/dex
  newName: ghcr.io/dexidp/dex
  newTag: v2.30.0
- name: quay.io/argoproj/argocd
  newName: quay.io/argoproj/argocd
  newTag: v2.1.2
- name: haproxy
  newName: haproxy
  newTag: 2.4.4-alpine
- name: redis
  newName: redis
  newTag: 6.2.5-alpine
