apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/DavidSpek/kubeflow/components/crud-web-apps/volumes/manifests/overlays/istio?ref=volumes-pvc-viewer

images:
  - name: davidspek/volumes-web-app
    newName: davidspek/volumes-web-app
    newTag: 0.5.4
    # digest: sha256:11539cbc16e7504e2512db99cc2283ec1a2119b855e17e79c2eecefecd751760
