apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/DavidSpek/kubeflow/components/pvcviewer-controller/config/overlays/kubeflow?ref=pvc-viewer-controller

images:
- name: davidspek/kubeflow-pvcviewer-controller
  newName: davidspek/kubeflow-pvcviewer-controller
  newTag: "0.7"
