apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/tf-operator/manifests/overlays/kubeflow?ref=3c207852c58662b8e0920e986fabad94298799bf # tag=v1.2.1

images:
- name: public.ecr.aws/j1r0q0g6/training/tf-operator
  newName: public.ecr.aws/j1r0q0g6/training/tf-operator
  newTag: 47a74b738920edbf4207160cec7e1dff9cdab3f2
